### ISSUE TITLE
Issue with libgraphbolt dynamic loading.

### ISSUE THREAD

**Issue by hmacdope** [conda-forge/dgl-feedstock#41]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I also ran into this issue with DGL 2.1.0 to do with the loader for libgraphbolt

https://discuss.dgl.ai/t/cannot-find-dgl-c-graphbolt-library/4429

### Installed packages

```shell
NA
```

### Environment info

```shell
NA
```

**Comment by zklaus** [comment]
Hm. To clarify: In the linked discussion, the user has DGL installed via pip from PyPI. This feedstock cannot do anything about that, since here we are providing an alternative means of installation that is not expected to be compatible. @hmacdope, are you encountering this issue with a conda-forge install of DGL?

**Comment by hmacdope** [comment]
@zklaus I also encountered this,  I think its an issue in our build.

to replicate

```bash
mamba create -n dgl_new
mamba install dgl
mamba install pyyaml pydantic  # missing from recipe, will make a separate issue
python -c "import dgl"
```

**Comment by zklaus** [comment]
Ok, I can replicate, but for me it is a slightly different issue. The dynamic loading code in `dgl/graphbolt/__init__.py` derives the version number for libgraphbolt from the torch version. Since we are not restricting the pytorch version in the run requirements, that version may be different from the version that was used in the build.

I.e. in the dgl package we have the file `libgraphbolt_pytorch_2.3.0.so` but since the pytorch update, it is now looking for `libgraphbolt_pytorch_2.3.0.so`. We can address that by using the `pin_compatible` jinja to pin the run requirements to whatever was used during the build. Question is: How tight do we need to be with libgraphbolt? Does it need to be the exact same version of pytorch? Or is same major and minor for example enough? In other words, do we expect what is now `libgraphbolt_pytorch_2.3.0.so` to work with pytorch 2.3.x, or only with 2.3.0?

**Comment by zklaus** [comment]
@conda-forge/dgl, if you have knowledge or an idea about actual runtime compatibility between libgraphbolt and pytorch versions, please let me know. For now, I will assume that it really must be the same and come up with a PR accordingly.

**Comment by mikemhenry** [comment]
We should raise this as an issue on the DGL repo since they might have a better idea of that, by this I mean this question:
> if you have knowledge or an idea about actual runtime compatibility between libgraphbolt and pytorch versions, please let me know. For now, I will assume that it really must be the same and come up with a PR accordingly.

**Comment by mfbalin** [comment]
> We should raise this as an issue on the DGL repo since they might have a better idea of that, by this I mean this question:
> 
> > if you have knowledge or an idea about actual runtime compatibility between libgraphbolt and pytorch versions, please let me know. For now, I will assume that it really must be the same and come up with a PR accordingly.

GraphBolt depends on the C++ API of torch and the answer to this question depends on what is recommended by torch. An answer is here: https://discuss.pytorch.org/t/version-compatability-scheme-for-pytorch-and-compiled-torch-extensions/164637/4?u=mfbalin and here: https://github.com/pytorch/pytorch/issues/88301#issuecomment-1300373052

@frozenbugs
